const ServicesTypes = {
  SET_SERVICES_WAITING_APPOINTMENT: 'SET_SERVICES_WAITING_APPOINTMENT',
  SET_SERVICES_DONE: 'SET_SERVICES_DONE',
  ACTIVE_SERVICE: 'ACTIVE_SERVICE'
};

export default ServicesTypes;